name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create application.properties
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Build Spring Boot application
        run: mvn clean install

      - name: Create deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Upload deployment package
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v2
        with:
          name: deploy

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: my-application
          environment_name: my-environment
          version_label: version-${{ github.run_number }}
          region: us-east-1
          deployment_package: deploy.zip
